version: "3.8"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_DATABASE: memo
        MYSQL_USER: root
        MYSQL_PASSWORD: pass
        MYSQL_ROOT_PASSWORD: pass
        DB_PORT: 3306
    ports:
        - 3306:3306
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - db
    environment:
      DISCORD_MEMO_TOKEN: __DISCORD_TOKEN__
      DB_HOST: db
      DB_NAME: memo
      DB_USER: root
      DB_PASS: pass
    volumes:
      - .:/workspace